services:
  forum-app:
    build:
      context: ../forum-app
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - forum-app
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    networks:
      - monitoring

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - "9093:9093"
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage: