groups:
  - name: forum_alerts
    rules:
      - alert: ForumDown
        expr: up{instance="forum-app:4000", job="forum-app"} == 0
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "Forum application is down"
          description: "Problem accessing http://forum-app:4000"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High HTTP Error Rate"
          description: "5xx error rate exceeds 5% for {{ $labels.instance }}"
      - alert: HighResponseLatency
        expr: histogram_quantile(0.95, rate(http_response_duration_seconds_bucket[5m])) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High response delay"
          description: "95th percentile response time is greater than 1 second for {{ $labels.instance }}"